#!/usr/bin/env python3
"""
Tests for PowerPoint generator functionality.
"""

import pytest
import asyncio
import tempfile
import os
from unittest.mock import AsyncMock, MagicMock, patch

from app.services.powerpoint_generator import PowerPointGenerator
from app.models.powerpoint_models import (
    PresentationConfig,
    PresentationMetadata,
    Slide,
    SlideType,
    LayoutType,
    SlideContent,
    TextContent,
    Rectangle,
    TextStyle,
    FontStyle,
    OutputFormat,
    Theme,
    ColorScheme,
    JobStatus
)


class TestPowerPointGenerator:
    """Test PowerPoint generation functionality."""
    
    def setup_method(self):
        """Set up test instance."""
        self.generator = PowerPointGenerator()
    
    @pytest.mark.asyncio
    async def test_generate_presentation_basic(self):
        """Test basic presentation generation."""
        # Create test configuration
        config = PresentationConfig(
            metadata=PresentationMetadata(
                title="Test Presentation",
                author="Test User",
                description="A test presentation"
            ),
            slides=[
                Slide(
                    title="Test Slide",
                    slide_type=SlideType.TITLE,
                    layout=LayoutType.TITLE_SLIDE,
                    content=SlideContent()
                )
            ],
            theme=Theme.OFFICE
        )
        
        data = {"test": "data"}
        
        with tempfile.TemporaryDirectory() as temp_dir:
            output_path = os.path.join(temp_dir, "test.pptx")
            
            # Mock database operations
            with patch('app.services.powerpoint_generator.execute_query', new_callable=AsyncMock):
                success, file_path, error = await self.generator.generate_presentation(
                    job_id=1,
                    user_id=1,
                    presentation_config=config,
                    output_format=OutputFormat.PPTX,
                    data_source=data
                )
            
            assert success is True
            assert error is None
            # Note: file_path will be generated by the service
    
    @pytest.mark.asyncio
    async def test_generate_presentation_with_text_content(self):
        """Test presentation generation with text content."""
        # Create slide with text content
        text_content = TextContent(
            text="Hello, World!",
            style=TextStyle(
                font=FontStyle(
                    family="Arial",
                    size=24,
                    bold=True,
                    color="#000000"
                ),
                alignment="center"
            ),
            position=Rectangle(x=1, y=2, width=8, height=1)
        )
        
        config = PresentationConfig(
            metadata=PresentationMetadata(
                title="Text Test",
                author="Test User"
            ),
            slides=[
                Slide(
                    title="Text Slide",
                    slide_type=SlideType.CONTENT,
                    layout=LayoutType.TITLE_AND_CONTENT,
                    content=SlideContent(texts=[text_content])
                )
            ],
            theme=Theme.MODERN
        )
        
        data = {}
        
        with tempfile.TemporaryDirectory() as temp_dir:
            output_path = os.path.join(temp_dir, "text_test.pptx")
            
            with patch('app.services.powerpoint_generator.execute_query', new_callable=AsyncMock):
                success, file_path, error = await self.generator.generate_presentation(
                    job_id=2,
                    user_id=1,
                    presentation_config=config,
                    output_format=OutputFormat.PPTX,
                    data_source=data
                )
            
            assert success is True
            assert error is None
    
    @pytest.mark.asyncio
    async def test_get_job_status(self):
        """Test job status tracking."""
        job_id = 123
        
        # Initially no status
        status = await self.generator.get_job_status(job_id)
        assert status is None
        
        # Simulate active job
        async with self.generator._lock:
            self.generator.active_jobs[job_id] = {
                "status": JobStatus.PROCESSING,
                "start_time": 1000,
                "current_slide": 1,
                "total_slides": 5
            }
        
        # Mock time.time to return predictable value
        with patch('time.time', return_value=1010):  # 10 seconds later
            status = await self.generator.get_job_status(job_id)
        
        assert status is not None
        assert status["job_id"] == job_id
        assert status["status"] == JobStatus.PROCESSING.value
        assert status["current_slide"] == 1
        assert status["total_slides"] == 5
        assert status["runtime_seconds"] == 10
        assert status["progress_percentage"] == 20.0  # 1/5 * 100
    
    @pytest.mark.asyncio
    async def test_cancel_job(self):
        """Test job cancellation."""
        job_id = 456
        
        # Initially job doesn't exist
        success = await self.generator.cancel_job(job_id)
        assert success is False
        
        # Add active job
        async with self.generator._lock:
            self.generator.active_jobs[job_id] = {
                "status": JobStatus.PROCESSING,
                "start_time": 1000,
                "current_slide": 1,
                "total_slides": 5
            }
        
        # Mock database update
        with patch('app.services.powerpoint_generator.execute_query', new_callable=AsyncMock):
            success = await self.generator.cancel_job(job_id)
        
        assert success is True
        
        # Check status is updated
        async with self.generator._lock:
            assert self.generator.active_jobs[job_id]["status"] == JobStatus.CANCELLED
    
    def test_get_layout_index(self):
        """Test layout index mapping."""
        # Test known layouts
        assert self.generator._get_layout_index(LayoutType.TITLE_SLIDE) == 0
        assert self.generator._get_layout_index(LayoutType.TITLE_AND_CONTENT) == 1
        assert self.generator._get_layout_index(LayoutType.TWO_CONTENT) == 3
        assert self.generator._get_layout_index(LayoutType.BLANK) == 6
    
    def test_get_chart_type(self):
        """Test chart type mapping."""
        from app.models.powerpoint_models import ChartType
        from pptx.enum.chart import XL_CHART_TYPE
        
        # Test known chart types
        assert self.generator._get_chart_type(ChartType.BAR) == XL_CHART_TYPE.BAR_CLUSTERED
        assert self.generator._get_chart_type(ChartType.COLUMN) == XL_CHART_TYPE.COLUMN_CLUSTERED
        assert self.generator._get_chart_type(ChartType.LINE) == XL_CHART_TYPE.LINE
        assert self.generator._get_chart_type(ChartType.PIE) == XL_CHART_TYPE.PIE
    
    @pytest.mark.asyncio
    async def test_count_charts(self):
        """Test chart counting functionality."""
        from app.models.powerpoint_models import Chart, ChartData, ChartConfig, ChartType
        
        # Create configuration with charts
        chart = Chart(
            data=ChartData(
                labels=["A", "B", "C"],
                datasets=[{"label": "Test", "data": [1, 2, 3]}]
            ),
            config=ChartConfig(chart_type=ChartType.BAR),
            position=Rectangle(x=1, y=2, width=6, height=4)
        )
        
        config = PresentationConfig(
            metadata=PresentationMetadata(title="Chart Test"),
            slides=[
                Slide(
                    title="Slide 1",
                    slide_type=SlideType.CHART,
                    layout=LayoutType.TITLE_AND_CONTENT,
                    content=SlideContent(charts=[chart])
                ),
                Slide(
                    title="Slide 2",
                    slide_type=SlideType.CHART,
                    layout=LayoutType.TITLE_AND_CONTENT,
                    content=SlideContent(charts=[chart, chart])  # Two charts
                )
            ]
        )
        
        count = await self.generator._count_charts(config)
        assert count == 3  # 1 + 2 charts
    
    @pytest.mark.asyncio
    async def test_count_animations(self):
        """Test animation counting functionality."""
        from app.models.powerpoint_models import AnimationType
        
        config = PresentationConfig(
            metadata=PresentationMetadata(title="Animation Test"),
            slides=[
                Slide(
                    title="Slide 1",
                    slide_type=SlideType.CONTENT,
                    layout=LayoutType.TITLE_AND_CONTENT,
                    animation=AnimationType.FADE,
                    content=SlideContent()
                ),
                Slide(
                    title="Slide 2",
                    slide_type=SlideType.CONTENT,
                    layout=LayoutType.TITLE_AND_CONTENT,
                    animation=AnimationType.NONE,  # No animation
                    content=SlideContent()
                ),
                Slide(
                    title="Slide 3",
                    slide_type=SlideType.CONTENT,
                    layout=LayoutType.TITLE_AND_CONTENT,
                    animation=AnimationType.SLIDE,
                    content=SlideContent()
                )
            ]
        )
        
        count = await self.generator._count_animations(config)
        assert count == 2  # Only slides with non-NONE animations
    
    @pytest.mark.asyncio
    async def test_load_image_http(self):
        """Test loading image from HTTP URL."""
        test_url = "http://example.com/image.png"
        test_content = b"fake image content"
        
        # Mock httpx response
        mock_response = MagicMock()
        mock_response.content = test_content
        mock_response.raise_for_status = MagicMock()
        
        mock_client = MagicMock()
        mock_client.__aenter__ = AsyncMock(return_value=mock_client)
        mock_client.__aexit__ = AsyncMock(return_value=None)
        mock_client.get = AsyncMock(return_value=mock_response)
        
        with patch('httpx.AsyncClient', return_value=mock_client):
            result = await self.generator._load_image(test_url)
        
        assert result == test_content
        mock_client.get.assert_called_once_with(test_url, timeout=30)
    
    @pytest.mark.asyncio
    async def test_load_image_file(self):
        """Test loading image from file path."""
        test_content = b"fake image content"
        
        with tempfile.NamedTemporaryFile(delete=False) as temp_file:
            temp_file.write(test_content)
            temp_file.flush()
            temp_path = temp_file.name
        
        try:
            result = await self.generator._load_image(temp_path)
            assert result == test_content
        finally:
            os.unlink(temp_path)
    
    @pytest.mark.asyncio
    async def test_fetch_data_static(self):
        """Test fetching data from static source."""
        data_source = {
            "static_source": {
                "data": {"key": "value", "items": [1, 2, 3]}
            }
        }
        
        result = await self.generator._fetch_data(data_source)
        assert result == {"key": "value", "items": [1, 2, 3]}
    
    @pytest.mark.asyncio
    async def test_fetch_data_empty(self):
        """Test fetching data from empty source."""
        data_source = {}
        
        result = await self.generator._fetch_data(data_source)
        assert result == {}
    
    @pytest.mark.asyncio
    async def test_update_job_progress(self):
        """Test job progress updates."""
        job_id = 789
        
        # Add active job
        async with self.generator._lock:
            self.generator.active_jobs[job_id] = {
                "status": JobStatus.PROCESSING,
                "start_time": 1000,
                "current_slide": 0,
                "total_slides": 0
            }
        
        # Update progress
        await self.generator._update_job_progress(job_id, 3, 10)
        
        # Check progress is updated
        async with self.generator._lock:
            job_info = self.generator.active_jobs[job_id]
            assert job_info["current_slide"] == 3
            assert job_info["total_slides"] == 10
    
    @pytest.mark.asyncio
    async def test_database_operations(self):
        """Test database operation calls."""
        job_id = 999
        
        # Mock execute_query
        with patch('app.services.powerpoint_generator.execute_query', new_callable=AsyncMock) as mock_query:
            # Test status update
            await self.generator._update_job_status(
                job_id,
                JobStatus.PROCESSING,
                started_at=None
            )
            
            # Verify query was called
            mock_query.assert_called()
            call_args = mock_query.call_args
            assert job_id in call_args[0]  # job_id should be in parameters
            assert JobStatus.PROCESSING.value in call_args[0]  # status should be in parameters
    
    @pytest.mark.asyncio
    async def test_error_handling(self):
        """Test error handling in generation."""
        config = PresentationConfig(
            metadata=PresentationMetadata(title="Error Test"),
            slides=[
                Slide(
                    title="Test Slide",
                    slide_type=SlideType.TITLE,
                    layout=LayoutType.TITLE_SLIDE,
                    content=SlideContent()
                )
            ]
        )
        
        # Mock database to raise an exception
        with patch('app.services.powerpoint_generator.execute_query', side_effect=Exception("Database error")):
            success, file_path, error = await self.generator.generate_presentation(
                job_id=1,
                user_id=1,
                presentation_config=config,
                output_format=OutputFormat.PPTX,
                data_source={}
            )
        
        assert success is False
        assert file_path is None
        assert error == "Database error"


class TestPowerPointGeneratorIntegration:
    """Integration tests for PowerPoint generator."""
    
    def setup_method(self):
        """Set up test instance."""
        self.generator = PowerPointGenerator()
    
    @pytest.mark.asyncio
    async def test_full_presentation_generation(self):
        """Test complete presentation generation flow."""
        # Create a comprehensive presentation config
        config = PresentationConfig(
            metadata=PresentationMetadata(
                title="Integration Test Presentation",
                author="Test Suite",
                description="A comprehensive test presentation",
                keywords=["test", "integration", "powerpoint"]
            ),
            slides=[
                # Title slide
                Slide(
                    title="Integration Test",
                    slide_type=SlideType.TITLE,
                    layout=LayoutType.TITLE_SLIDE,
                    content=SlideContent()
                ),
                # Content slide with text
                Slide(
                    title="Test Content",
                    slide_type=SlideType.CONTENT,
                    layout=LayoutType.TITLE_AND_CONTENT,
                    content=SlideContent(
                        texts=[
                            TextContent(
                                text="This is a test slide with formatted text.",
                                style=TextStyle(
                                    font=FontStyle(
                                        family="Calibri",
                                        size=18,
                                        bold=True,
                                        color="#1f4e79"
                                    ),
                                    alignment="left"
                                ),
                                position=Rectangle(x=1, y=2.5, width=8, height=2)
                            )
                        ]
                    )
                )
            ],
            theme=Theme.OFFICE,
            color_scheme=ColorScheme.BLUE
        )
        
        data_source = {
            "static_source": {
                "data": {"test_data": [1, 2, 3, 4, 5]}
            }
        }
        
        with tempfile.TemporaryDirectory() as temp_dir:
            # Mock all database operations
            with patch('app.services.powerpoint_generator.execute_query', new_callable=AsyncMock):
                success, file_path, error = await self.generator.generate_presentation(
                    job_id=100,
                    user_id=1,
                    presentation_config=config,
                    output_format=OutputFormat.PPTX,
                    data_source=data_source
                )
            
            # Verify successful generation
            assert success is True
            assert error is None
            assert file_path is not None
            
            # Note: In a real integration test, we would verify the actual file
            # exists and contains the expected content, but that requires
            # a full database setup and file system access


if __name__ == "__main__":
    pytest.main([__file__, "-v"])