-- Initialize Word Export Service Database
-- This script sets up the initial database schema and data

-- Create extensions if they don't exist
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Create indexes for better performance
-- (Tables are created automatically by SQLAlchemy, these are additional indexes)

-- Performance indexes for word_export_jobs
CREATE INDEX IF NOT EXISTS idx_word_export_jobs_user_id_status 
ON word_export_jobs(user_id, status);

CREATE INDEX IF NOT EXISTS idx_word_export_jobs_created_at 
ON word_export_jobs(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_word_export_jobs_expires_at 
ON word_export_jobs(expires_at) 
WHERE expires_at IS NOT NULL;

-- Performance indexes for word_templates
CREATE INDEX IF NOT EXISTS idx_word_templates_type_active 
ON word_templates(template_type, is_active) 
WHERE is_active = true;

-- Performance indexes for word_export_analytics
CREATE INDEX IF NOT EXISTS idx_word_export_analytics_user_event 
ON word_export_analytics(user_id, event_type);

CREATE INDEX IF NOT EXISTS idx_word_export_analytics_created_at 
ON word_export_analytics(created_at DESC);

-- Insert default templates
INSERT INTO word_templates (name, description, template_type, template_data, is_default, is_active, created_by, created_at, updated_at) 
VALUES 
  (
    'Professional Default',
    'Professional business document template with clean formatting',
    'professional',
    '{
      "default_font": {
        "family": "Calibri",
        "size": 11,
        "bold": false,
        "italic": false,
        "color": "#000000"
      },
      "color_scheme": "blue",
      "page_setup": {
        "orientation": "portrait",
        "margins": {
          "top": 1.0,
          "bottom": 1.0,
          "left": 1.0,
          "right": 1.0
        }
      },
      "header": {
        "text": "Professional Document",
        "include_page_number": true,
        "include_date": false,
        "alignment": "center"
      },
      "footer": {
        "text": "Generated by Word Export Service",
        "include_page_number": true,
        "include_date": true,
        "alignment": "center"
      }
    }',
    true,
    true,
    0,
    NOW(),
    NOW()
  ),
  (
    'Corporate Default',
    'Corporate document template with formal styling',
    'corporate',
    '{
      "default_font": {
        "family": "Times New Roman",
        "size": 12,
        "bold": false,
        "italic": false,
        "color": "#000000"
      },
      "color_scheme": "red",
      "page_setup": {
        "orientation": "portrait",
        "margins": {
          "top": 1.0,
          "bottom": 1.0,
          "left": 1.25,
          "right": 1.25
        }
      },
      "header": {
        "text": "Corporate Report",
        "include_page_number": false,
        "include_date": true,
        "alignment": "right"
      },
      "footer": {
        "text": "Confidential",
        "include_page_number": true,
        "include_date": false,
        "alignment": "center"
      }
    }',
    false,
    true,
    0,
    NOW(),
    NOW()
  ),
  (
    'Academic Default',
    'Academic paper template with standard formatting',
    'academic',
    '{
      "default_font": {
        "family": "Times New Roman",
        "size": 12,
        "bold": false,
        "italic": false,
        "color": "#000000"
      },
      "color_scheme": "green",
      "page_setup": {
        "orientation": "portrait",
        "margins": {
          "top": 1.0,
          "bottom": 1.0,
          "left": 1.0,
          "right": 1.0
        }
      },
      "header": null,
      "footer": {
        "text": "",
        "include_page_number": true,
        "include_date": false,
        "alignment": "center"
      }
    }',
    false,
    true,
    0,
    NOW(),
    NOW()
  ),
  (
    'Report Default',
    'Technical report template with structured formatting',
    'report',
    '{
      "default_font": {
        "family": "Arial",
        "size": 11,
        "bold": false,
        "italic": false,
        "color": "#000000"
      },
      "color_scheme": "orange",
      "page_setup": {
        "orientation": "portrait",
        "margins": {
          "top": 1.0,
          "bottom": 1.0,
          "left": 1.0,
          "right": 1.0
        }
      },
      "header": {
        "text": "Technical Report",
        "include_page_number": false,
        "include_date": true,
        "alignment": "left"
      },
      "footer": {
        "text": "Report Generated",
        "include_page_number": true,
        "include_date": true,
        "alignment": "center"
      }
    }',
    false,
    true,
    0,
    NOW(),
    NOW()
  ),
  (
    'Minimal Default',
    'Minimal document template with clean, simple formatting',
    'minimal',
    '{
      "default_font": {
        "family": "Calibri",
        "size": 11,
        "bold": false,
        "italic": false,
        "color": "#000000"
      },
      "color_scheme": "monochrome",
      "page_setup": {
        "orientation": "portrait",
        "margins": {
          "top": 0.75,
          "bottom": 0.75,
          "left": 0.75,
          "right": 0.75
        }
      },
      "header": null,
      "footer": {
        "text": "",
        "include_page_number": true,
        "include_date": false,
        "alignment": "right"
      }
    }',
    false,
    true,
    0,
    NOW(),
    NOW()
  )
ON CONFLICT (name) DO NOTHING;

-- Create triggers for automatic timestamp updates
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Apply trigger to word_templates table
DROP TRIGGER IF EXISTS update_word_templates_updated_at ON word_templates;
CREATE TRIGGER update_word_templates_updated_at
    BEFORE UPDATE ON word_templates
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Create function for cleanup of expired jobs
CREATE OR REPLACE FUNCTION cleanup_expired_jobs()
RETURNS INTEGER AS $$
DECLARE
    deleted_count INTEGER;
BEGIN
    -- Delete expired jobs and their associated files
    DELETE FROM word_export_jobs 
    WHERE expires_at IS NOT NULL 
      AND expires_at < NOW() 
      AND status IN ('completed', 'failed');
    
    GET DIAGNOSTICS deleted_count = ROW_COUNT;
    
    -- Log the cleanup operation
    INSERT INTO word_export_analytics (user_id, job_id, event_type, event_data, created_at)
    VALUES (0, 0, 'cleanup_expired_jobs', json_build_object('deleted_count', deleted_count), NOW());
    
    RETURN deleted_count;
END;
$$ LANGUAGE plpgsql;

-- Grant necessary permissions
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO wordservice;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO wordservice;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO wordservice;

-- Insert initial analytics event
INSERT INTO word_export_analytics (user_id, job_id, event_type, event_data, created_at)
VALUES (0, 0, 'database_initialized', json_build_object('timestamp', NOW()), NOW());

-- Display initialization summary
DO $$
DECLARE
    template_count INTEGER;
BEGIN
    SELECT COUNT(*) INTO template_count FROM word_templates WHERE is_active = true;
    
    RAISE NOTICE 'Word Export Service database initialized successfully';
    RAISE NOTICE 'Active templates: %', template_count;
    RAISE NOTICE 'Database version: %', version();
    RAISE NOTICE 'Initialization completed at: %', NOW();
END $$;